### ISSUE TITLE
ftp_fget error connecting to BunnyCDN with v3.1.0

### ISSUE THREAD

**Issue by selvinkuik** [Simply-Static/simply-static#178]
Getting the stack trace below when trying to generate static...

```
[2023-10-05 09:12:13] Setting up
[2023-10-05 09:12:16] Fetched 1058 of 1058 pages/files
[2023-10-05 09:14:23] Error: (1) Uncaught TypeError: ftp_fget(): Argument #1 ($ftp) must be of type resource, null given in /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php:146
Stack trace:
#0 /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php(146): ftp_fget()
#1 /var/www/html/wp-content/plugins/simply-static-pro/src/deployment/bunny-cdn/class-ssp-bunny-updater.php(165): WP_Filesystem_FTPext->get_contents()
#2 /var/www/html/wp-content/plugins/simply-static-pro/src/deployment/bunny-cdn/class-ssp-bunny-deploy-task.php(124): simply_static_pro\Bunny_Updater::upload_file()
#3 /var/www/html/wp-content/plugins/simply-static-pro/src/deployment/bunny-cdn/class-ssp-bunny-deploy-task.php(56): simply_static_pro\Bunny_Deploy_Task->upload_static_files()
#4 /var/www/html/wp-content/plugins/simply-static/src/class-ss-archive-creation-job.php(146): simply_static_pro\Bunny_Deploy_Task->perform()
#5 /var/www/html/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(514): Simply_Static\Archive_Creation_Job->task()
#6 /var/www/html/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(335): WP_Background_Process->handle()
#7 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Background_Process->maybe_handle()
#8 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#9 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#10 /var/www/html/wp-admin/admin-ajax.php(203): do_action()
#11 {main}
  thrown in /var/www/html/wp-admin/includes/class-wp-filesystem-ftpext.php on line 146
```

**Comment by patrickposner** [comment]
Hey @selvinkuik,

I assume you're running on an older version of Simply Static Pro, right?

We entirely refactored the BunnyCDN deployment integration in 1.3 of Simply Static Pro.

With that, we no longer require the ability of FTP support within PHP on the server and instead work directly with the WP HTTP API and the endpoint from the BunnyCDN API (which is also a lot faster compared to the older implementation).

So updating should help! :-)

Cheers,
Patrick

**Comment by selvinkuik** [comment]
Yea, my versions:

- Simply Static v3.1.0
- Simply Static Pro v1.4.5.6

Is there a configuration I need to set to disable FTP in Simply Static?
