### ISSUE TITLE
Incompatibility issue with Polylang 3.5.4

### ISSUE THREAD

**Issue by ilkkarinne** [Simply-Static/simply-static#213]
I'm getting a PHP Fatal error when trying to save any of the Simply Static configuration options if the ```archive_status_messages``` WP option is non-empty:
```
[26-Feb-2024 19:16:19 UTC] PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in /opt/bitnami/wordpress/wp-includes/pomo/translations.php:92
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/pomo/translations.php(107): Translations->translate_entry()
#1 /bitnami/wordpress/wp-content/plugins/polylang/include/translate-option.php(378): Translations->translate()
#2 /bitnami/wordpress/wp-content/plugins/polylang/include/translate-option.php(341): PLL_Translate_Option->check_value_recursive()
#3 /bitnami/wordpress/wp-content/plugins/polylang/include/translate-option.php(275): PLL_Translate_Option->check_value_recursive()
#4 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(324): PLL_Translate_Option->pre_update_option()
#5 /opt/bitnami/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#6 /opt/bitnami/wordpress/wp-includes/option.php(773): apply_filters()
#7 /bitnami/wordpress/wp-content/plugins/simply-static/src/admin/inc/class-ss-admin-settings.php(365): update_option()
#8 /opt/bitnami/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1193): Simply_Static\Admin_Settings->save_settings()
#9 /opt/bitnami/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1041): WP_REST_Server->respond_to_request()
#10 /opt/bitnami/wordpress/wp-includes/rest-api/class-wp-rest-server.php(431): WP_REST_Server->dispatch()
#11 /opt/bitnami/wordpress/wp-includes/rest-api.php(424): WP_REST_Server->serve_request()
#12 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(324): rest_api_loaded()
#13 /opt/bitnami/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#14 /opt/bitnami/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action()
#15 /opt/bitnami/wordpress/wp-includes/class-wp.php(418): do_action_ref_array()
#16 /opt/bitnami/wordpress/wp-includes/class-wp.php(813): WP->parse_request()
#17 /opt/bitnami/wordpress/wp-includes/functions.php(1336): WP->main()
#18 /opt/bitnami/wordpress/wp-blog-header.php(16): wp()
#19 /opt/bitnami/wordpress/index.php(17): require('...')
#20 {main}
  thrown in /opt/bitnami/wordpress/wp-includes/pomo/translations.php on line 92
```

The culprit seems to be, that the WP option ```archive_status_messages``` contains the activity message log as object of objects, to which the Polylang code in file [polylang/include/translate-option.php on line 378](https://github.com/polylang/polylang/blob/3.5.4/include/translate-option.php#L378) is not prepared for (the variable $old_values has and Array value, and it's used used as an array index).

```print_p($old_values)``` yields:
```php
Array
(
    [setup] => Array
        (
            [message] => Setting up
            [datetime] => 2024-02-27 13:01:36
        )
                                                    
    [fetch_urls] => Array
        (
            [message] => Fetched 56 of 441 pages/files
            [datetime] => 2024-02-27 13:01:37
        )
                                                                                                    
    [done] => Array
        (
            [message] => Done! Finished in 00:00:08
            [datetime] => 2024-02-27 13:01:44
        )

);
```
Simply Status Settings Export:
```json
{
    "_locale": "user",
    "input_-2": "<REDACTED>",
    "input_-1": "<REDACTED>",
    "destination_scheme": "https://",
    "destination_host": "",
    "temp_files_dir": "/opt/bitnami/wordpress/wp-content/uploads/simply-static/temp-files/",
    "additional_urls": "",
    "additional_files": "",
    "urls_to_exclude": "wp-json\nwp-login.php",
    "delivery_method": "github",
    "local_dir": "",
    "relative_path": "",
    "destination_url_type": "relative",
    "debugging_mode": true,
    "http_basic_auth_username": "",
    "http_basic_auth_password": "",
    "origin_url": "",
    "version": "3.1.6",
    "force_replace_url": "",
    "clear_directory_before_export": "",
    "ssh_security_token": "",
    "ssh_use_forms": "1",
    "ssh_404_page_id": "",
    "ssh_thank_you_page_id": "",
    "tiiny_email": "<REDACTED>",
    "tiiny_subdomain": "",
    "tiiny_domain_suffix": "tiiny.site",
    "tiiny_password": "",
    "cdn_api_key": "",
    "cdn_storage_host": "storage.bunnycdn.com",
    "cdn_access_key": "",
    "cdn_pull_zone": "",
    "cdn_storage_zone": "",
    "cdn_directory": "",
    "cdn_404": "",
    "github_account_type": "organization",
    "github_user": "<REDACTED>",
    "github_email": "<REDACTED>",
    "github_personal_access_token": "<REDACTED>",
    "github_repository": "<REDACTED>",
    "github_repository_visibility": "private",
    "github_branch": "main",
    "github_webhook_url": "<REDACTED>",
    "github_folder_path": "",
    "aws_region": "<REDACTED>",
    "aws_access_key": "<REDACTED>",
    "aws_access_secret": "<REDACTED>",
    "aws_bucket": "<REDACTED>",
    "aws_subdirectory": "",
    "aws_distribution_id": "",
    "aws_empty": "",
    "digitalocean_key": "",
    "digitalocean_secret": "",
    "digitalocean_bucket": "",
    "digitalocean_region": "",
    "fix_cors": "allowed_http_origins",
    "static_url": "<REDACTED>",
    "use_forms": "",
    "use_comments": "",
    "comment_redirect": "",
    "use_search": "1",
    "search_type": "fuse",
    "search_index_title": "#header h1",
    "search_index_content": "#content p",
    "search_index_excerpt": "",
    "search_excludable": "",
    "search_metadata": "",
    "fuse_selector": ".wp-block-search__input",
    "algolia_app_id": "",
    "algolia_admin_api_key": "",
    "algolia_search_api_key": "",
    "algolia_index": "simply_static",
    "algolia_selector": ".search-field",
    "use_minify": "1",
    "minify_html": "",
    "minify_css": "1",
    "minify_inline_css": "1",
    "minify_js": "1",
    "minify_inline_js": "1",
    "generate_404": "1",
    "wp_content_folder": "",
    "wp_includes_folder": "",
    "wp_uploads_folder": "",
    "wp_plugins_folder": "",
    "wp_themes_folder": "",
    "theme_style_name": "style",
    "rename_plugin_folders": "",
    "author_url": "people",
    "hide_rest_api": "1",
    "hide_style_id": "1",
    "hide_comments": "",
    "hide_version": "1",
    "hide_generator": "1",
    "hide_prefetch": "",
    "hide_rsd": "",
    "hide_emotes": "1",
    "disable_xmlrpc": "1",
    "disable_embed": "",
    "disable_db_debug": "1",
    "disable_wlw_manifest": "1",
    "http_basic_auth_digest": "",
    "archive_status_messages": {
        "setup": {
            "message": "Setting up",
            "datetime": "2024-02-27 13:01:36"
        },
        "fetch_urls": {
            "message": "Fetched 56 of 441 pages/files",
            "datetime": "2024-02-27 13:01:37"
        },
        "done": {
            "message": "Done! Finished in 00:00:08",
            "datetime": "2024-02-27 13:01:44"
        }
    },
    "archive_name": "simply-static-1-1709031696",
    "archive_start_time": "2024-02-27 13:01:36",
    "archive_end_time": "2024-02-27 13:01:44",
    "pages_status": {
        "remaining": 1,
        "total": 441
    },
    "encryption_key": "<REDACTED>",
    "core-installed": "1",
    "wp_content_directory": "wp-content",
    "wp_includes_directory": "wp-includes",
    "wp_uploads_directory": "wp-content/uploads",
    "wp_plugins_directory": "wp-content/plugins",
    "wp_themes_directory": "wp-content/themes"
}
```
 
This could be either a bug in Polylang or Simply Static, or just an incompatibility issue, I'm not educated enough to guess.

I have tested this with no unmodified Twenty Twenty-Four theme v1.0, and only the following plugins activated:
* Polylang	Version 3.5.4 by WP SYNTEX 
* Simply Static	Version 3.1.6.1 by Patrick Posner 
* Simply Static Pro	Version 1.4.7 by Patrick Posner

**Comment by ilkkarinne** [comment]
The issue seems to go away, when disabling Simply Static Pro WPML translations by renaming the file ```/plugins/simply-static-pro/wpml-config.xml``` to ```/plugins/simply-static-pro/wpml-config.xml.disabled```
