### ISSUE TITLE
Failed to export on WP 6.7 running on EasyWP

### ISSUE THREAD

**Issue by mpint** [Simply-Static/simply-static#278]
Hi, I'm running into the following error when trying to export a freshly generated WP site to ZIP.

```
Error: (1) Uncaught Error: Call to undefined function php_uname() in /var/www/wptbox/wp-admin/includes/class-pclzip.php:5717
```

Activity Log tail
```
[2024-11-17 21:51:11] [class-ss-archive-creation-job.php:170] This task is done and there are no more tasks, time to complete the job
[2024-11-17 21:51:11] [class-ss-archive-creation-job.php:197] Completing the job
[2024-11-17 21:51:11] [class-ss-archive-creation-job.php:324] Status message: [done] Done! Finished in 00:00:03
[2024-11-17 21:51:11] [class-ss-archive-creation-job.php:384] Error: (1) Uncaught Error: Call to undefined function php_uname() in /var/www/wptbox/wp-admin/includes/class-pclzip.php:5717Stack trace:#0 /var/www/wptbox/wp-admin/includes/class-pclzip.php(1463): PclZipUtilTranslateWinPath()#1 /var/www/wptbox/wp-admin/includes/class-pclzip.php(312): PclZip->privParseOptions()#2 /var/www/wptbox/wp-content/plugins/simply-static/src/tasks/class-ss-create-zip-archive.php(89): PclZip->create()#3 /var/www/wptbox/wp-content/plugins/simply-static/src/tasks/class-ss-create-zip-archive.php(25): Simply_Static\Create_Zip_Archive_Task->create_zip()#4 /var/www/wptbox/wp-content/plugins/simply-static/src/class-ss-archive-creation-job.php(154): Simply_Static\Create_Zip_Archive_Task->perform()#5 /var/www/wptbox/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(531): Simply_Static\Archive_Creation_Job->task()#6 /var/www/wptbox/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(350): WP_Background_Process->handle()#7 /var/www/wptbox/wp-includes/class-wp-hook.php(324): WP_Background_Process->maybe_handle()#8 /var/www/wptbox/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#9 /var/www/wptbox/wp-includes/plugin.php(517): WP_Hook->do_action()#10 /var/www/wptbox/wp-admin/admin-ajax.php(192): do_action()#11 {main}  thrown in <b>/var/www/wptbox/wp-admin/includes/class-pclzip.php</b> on line <b>5717</b>
[2024-11-17 21:51:11] [class-ss-archive-creation-job.php:324] Status message: [error] Error: (1) Uncaught Error: Call to undefined function php_uname() in /var/www/wptbox/wp-admin/includes/class-pclzip.php:5717Stack trace:#0 /var/www/wptbox/wp-admin/includes/class-pclzip.php(1463): PclZipUtilTranslateWinPath()#1 /var/www/wptbox/wp-admin/includes/class-pclzip.php(312): PclZip->privParseOptions()#2 /var/www/wptbox/wp-content/plugins/simply-static/src/tasks/class-ss-create-zip-archive.php(89): PclZip->create()#3 /var/www/wptbox/wp-content/plugins/simply-static/src/tasks/class-ss-create-zip-archive.php(25): Simply_Static\Create_Zip_Archive_Task->create_zip()#4 /var/www/wptbox/wp-content/plugins/simply-static/src/class-ss-archive-creation-job.php(154): Simply_Static\Create_Zip_Archive_Task->perform()#5 /var/www/wptbox/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(531): Simply_Static\Archive_Creation_Job->task()#6 /var/www/wptbox/wp-content/plugins/simply-static/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(350): WP_Background_Process->handle()#7 /var/www/wptbox/wp-includes/class-wp-hook.php(324): WP_Background_Process->maybe_handle()#8 /var/www/wptbox/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#9 /var/www/wptbox/wp-includes/plugin.php(517): WP_Hook->do_action()#10 /var/www/wptbox/wp-admin/admin-ajax.php(192): do_action()#11 {main}  thrown in <b>/var/www/wptbox/wp-admin/includes/class-pclzip.php</b> on line <b>5717</b>
```

Full errors logs are available if needed.

SimplyStatic Version: 3.2.4.1
WP Version: 6.7

**Comment by mpint** [comment]
Thanks for the quick reply Patrick. We are using SimplyStatic Pro to deploy on Cloudflare Pages, so we only care about low costs and large storage from a WP provider.  Could you recommend any EasyWP alternatives that offer large storage and low costs?

**Comment by patrickposner** [comment]
@mpint understandable!

What about SpinupWP: https://spinupwp.com/

We use that (alongside Digital Ocean), and it works pretty well with all the features Simply Static and Simply Static Pro provide.

It also doesn't need any customization - their setup works out of the box!

**Comment by mpint** [comment]
Thanks for the recommendation, will look into them. Do you know if Dreamhost is compatible?
